### ISSUE TITLE
option --cpu-type invalid choice: 'inorder'  

### ISSUE THREAD

**Issue by yao5461** [gem5/gem5#1]
Hi,
I have a problem setting cup-type to 'inorder'. The command line:
    ./build/X86/gem5.opt ./configs/example/fs.py --script=./scripts/x264/x264_64c_simsmall.rcS \
    -n 4 --cpu-type inorder --mem-size=2GB --caches --l2cache 
The error message:
          fs.py: error: option --cpu-type: invalid choice: 'inorder' (choose from 'arm_detailed',  'AtomicSimpleCPU', 'X86KvmCPU', 'DerivO3CPU', 'TimingSimpleCPU', 'timing', 'detailed', 'kvm', 'atomic')

How to run the simulator with inorder CPU? I'm a new user for Gem5.
The InOrderCpu has been implemented. Right? (src/cpu/inorder)
Thanks.

Best Regards,
Yao Liu

**Comment by ennobler** [comment]
The Inorder CPU doesn’t work for X86.


Ali
