### ISSUE TITLE
Attribute Error in Full System Simulation

### ISSUE THREAD

**Issue by sabbaghm** [gem5/gem5#10]
Hi,

I am trying to run a x86 Full System Simulation on _Ubuntu 16.04_ that is hosted on a _X86_64_ machine, however with any configuration file, even the example _fs.py_, I see the following error:

**command line: build/X86/gem5.opt configs/example/fs.py

Global frequency set at 1000000000000 ticks per second
Error in unproxying param 'device' of system.pc.com_1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/gem5/src/python/m5/main.py", line 433, in main
    exec filecode in scope
  File "configs/example/fs.py", line 372, in <module>
    Simulation.run(options, root, test_sys, FutureClass)
  File "/apps/gem5/configs/common/Simulation.py", line 589, in run
    m5.instantiate(checkpoint_dir)
  File "/apps/gem5/src/python/m5/simulate.py", line 90, in instantiate
    for obj in root.descendants(): obj.unproxyParams()
  File "/apps/gem5/src/python/m5/SimObject.py", line 1332, in unproxyParams
    value = value.unproxy(self)
  File "/apps/gem5/src/python/m5/proxy.py", line 101, in unproxy
    (self.path(), self._pdesc.ptype_str, base.path())
AttributeError: Can't resolve proxy 'any' of type 'SerialDevice' from 'system.pc.com_1'**

I am using the latest _gem5_ from github and following the steps listed here for setup:
[http://gem5.org/Running_gem5](url)
[http://learning.gem5.org/book/part4/intro.html](url)
Could you help with resolving this issue?

Thanks,

Majid

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
