### ISSUE TITLE
cpu-kvm: KVM CPU reports zero instructions simulated when running on Intel Alder Lake host

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#1064]
**Describe the bug**
When running the X86KvmCPU on an E-core on an Intel Alder Lake host, the Kvm CPU reports zero instructions simulated. This  makes it impossible to schedule exits after N instructions to take a checkpoint, for example. 

The problem is that on hybrid architectures like Intel Alder Lake, there are multiple types of cores, each of which have their own set of supported hardware performance counters (i.e., performance counters of type PERF_TYPE_HARDWARE). Linux supports only creating a hardware performance counter for either a P-core or E-core, but not both. Furthermore, by default, all hardware performance counters created are bound to P-cores, not E-cores. Since the X86KvmCPU is not aware of this, it binds its performance counters implicitly to P-cores. If gem5 runs on an E-core, then these P-core counters are never enabled, thus always returning zero when read from.

**Affects version**
develop @ [1153223](https://github.com/gem5/gem5/commit/115322319c709a6e2a12e8b5c5299aa813d94633)

**gem5 Modifications**
None

**To Reproduce**
1. Compile gem5: `scons build/X86/gem5.opt`
2. Run the built-in hello world on an E-core of an Intel Alder Lake or Raptor Lake system (where CPU 23 is an E-core): `taskset -c 23 ./build/X86/gem5.opt configs/deprecated/example/se.py --cpu-type=X86KvmCPU -c tests/test-progs/hello/bin/x86/linux/hello`
3. Check the number of simInsts: `grep simInsts m5out/stats.txt`

**Terminal Output**
```
$ grep simInsts m5out/stats.txt
```
That is, simInsts isn't even present in m5out/stats.txt (since it's zero and thus omitted).

**Expected behavior**
The number of simInsts should be nonzero.

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86, Intel Alder Lake

**Compiler used**
GCC 11.4.0

**Additional information**
I will submit a patch for this shortly

**Comment by ivanaamit** [comment]
Reopening this issue because we needed to revert the pushed change.
