### ISSUE TITLE
The registered Python class cannot be recognized and imported during the compilation of the library.

### ISSUE THREAD

**Issue by despotx** [gem5/gem5#1125]
I have registered a Python class using SimObject within the Sconscript file, and this class is callable within scripts. However, when I attempted to integrate this class into the library and recompiled, I received a ModuleNotFoundError. Is there any additional implicit definition required to register a Python class as a module? I have searched extensively and examined many Python classes that can be imported as modules, but I have not discovered any particular distinctions.
I would greatly appreciate any help that's possible.

**Comment by ivanaamit** [comment]
@despotx, could you please provide your code? Thanks.
