### ISSUE TITLE
broken docker pull ghcr.io/gem5ubuntu-20.04_all-dependencies:v23-0

### ISSUE THREAD

**Issue by deojo** [gem5/gem5#1174]
The docker image for Ubuntu 20.04 in the documentation is an incorrect version. It redirects to 404 Page not found, and while pulling it via docker it says it doesn't exist. It should redirect to version 23:1 but the doc says its version 23:0. Documentation needs to update this.

Affects Ubuntu 20.04

Steps to reproduce the behavior. Please assume starting from a clean repository:

    docker pull "ubuntu 20.04 image"
    Error: image not found

**Affects version**
all

**To Reproduce**
docker pull ghcr.io/gem5ubuntu-20.04_all-dependencies:v23-0

**output / error response**
Error response from daemon: Head "https://ghcr.io/v2/gem5ubuntu-20.04_all-dependencies/manifests/v23-0": name invalid

**Comment by ivanaamit** [comment]
@deojo, Thank you for reporting this! The bug should be fixed now. I will close this issue, but please feel free to reopen it if it is not solved.
