### ISSUE TITLE
gem5 gcn3 vega run database

### ISSUE THREAD

**Issue by Yongze-zzz** [gem5/gem5#1194]
Hello, gem5-gcn3 ​​vega authors. I'm a database practitioner, trying to figure out how database software behaves under unified memory. I used an older version of gem5-gpu full-system mode to run the rodinia benchmark (but it produced unsolvable problems). I tried to run the square example using gem5-gcn3 ​​vega's apu_se.py, and it worked fine on my computer. I'm curious about how gem5-gcn3 ​​vega runs gpu full-system mode? It supports both cpu-side calling pthreads and gpu-side executing kernel functions. But I have a hard time understanding gem5, can you give me some advice?

**Comment by mattsinc** [comment]
@Yongze-zzz : I'm not sure I fully understand your question, but @abmerop put together instructions on installing GPUFS here: https://github.com/gem5/gem5-resources/blob/stable/src/x86-ubuntu-gpu-ml/BUILDING.md.  I think this is what you are looking for?

**Comment by Yongze-zzz** [comment]
Running ./build.sh on my system produced the following problem：qemu.initialize: Error determining qemu version: exit status 1.
![image](https://github.com/gem5/gem5/assets/70116723/28fb332f-c81f-4791-8035-2c1a653c0bc0)

Then I try to run "qemu-system-x86_64 --version" ,it reported like below

![image](https://github.com/gem5/gem5/assets/70116723/cfbb6e91-5d0e-4a5e-9553-1ae984029cc5)

**Comment by mattsinc** [comment]
@abmerop can you help with this?  I am not an expert with your scripts yet.

**Comment by abmerop** [comment]
Do the other disk images also fail to build?  I assume they would since this is a copy with additional packages.  In that case it is not specific to gpu.

**Comment by Yongze-zzz** [comment]
Yes,abmerop is right. I tried running build.sh under x86-ubuntu and had the same problem. It seems that my qemu software is not a specific version,  I have trouble finding a version that can support normal builds on my system.

**Comment by Yongze-zzz** [comment]
How to run gem5-gcn3-vega full system mode?

**Comment by abmerop** [comment]
There is a pre-built disk image that will be available on next release.  You could try that on the develop branch.  To do that you could try to follow the steps "To Reproduce" in this issue: https://github.com/gem5/gem5/issues/1195 .

**Comment by Yongze-zzz** [comment]
I run  build/VEGA_X86/gem5.opt configs/example/gpufs/runfs.py --disk-image ../gem5-resources/src/x86-ubuntu-gpu-ml/disk-image/x86-ubuntu-gpu-ml --kernel ../gem5-resources/src/x86-ubuntu-gpu-ml/vmlinux-gpu-ml --gpu-mmio-trace ../gem5-resources/src/gpu-fs/vega_mmio.log. Than the system reports :panic: Need at least 2GB of system memory to load amdgpu module. My CPU is Intel 8360H and GPU is nvidia tesla t4. Does the simulator support to simulate amdgpu based on the nvidia physical device?

**Comment by abmerop** [comment]
No physical GPU is required, it is a simulated device.

I would recommend using the `configs/example/gpufs/vega10_kvm.py` helper script if you are on stable.  If you are on the develop branch I would recommended using either `configs/example/gpufs/mi200.py` or `configs/example/gpufs/mi300.py`

Those helper scripts will set the memory size for you to avoid the error you are seeing.  If you want to use `runfs.py` you'll have to add at least `--mem-size=8GB` or anything >2GB.
