### ISSUE TITLE
The "range" in memory.py:201 causes a TypeError

### ISSUE THREAD

**Issue by llamster** [gem5/gem5#1228]
When calling `set_memory_range` in components/memory/memory.py with a list of memory ranges that contains more than one range, the exception that should be raised is not raised as the line 201 contains a typo. Instead of `range[0]`, it should read `ranges[0]`. As `range` refers to a type, a TypeError is thrown instead. 
Changing range to `ranges[0]` fixes the issue and produces the expected behavior.

**Comment by ivanaamit** [comment]
Hi @llamster, thank you for reporting this. However, it was fixed in #855. The change is currently visible on the develop branch.
