### ISSUE TITLE
Default values of "apu_se.py" don't work

### ISSUE THREAD

**Issue by cyk0521** [gem5/gem5#13]
I've been tried to run HSAIL_X86 arch by "scons build/HSAIL_X86/gem5.opt" and running with "config/examples/apu_se.py" configuration.
I installed CLOC compiler binaries and HSA-runtime package which are mentioned in https://github.com/HSAFoundation/CLOC/blob/cf777856cfce86d11ea97c245992971159b85a4d/INSTALL.md.
And then, with compiled binary (HelloWorld) and generated GPU kernel binary (hw.asm), I tried to run APU simulation.
However, it didn't work and printed messeages as follows:

> choi@choi-desktop:~/Simulator/gem5$ build/HSAIL_X86/gem5.opt configs/example/apu_se.py -c ~/Simulator/CLOC/examples/snack/helloworld/HelloWorld -k ~/Simulator/CLOC/examples/snack/helloworld/hw.asm
gem5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.

> gem5 compiled Dec 28 2017 13:59:23
gem5 started Dec 29 2017 15:47:08
gem5 executing on choi-desktop, pid 11084
command line: build/HSAIL_X86/gem5.opt configs/example/apu_se.py -c /home/choi/Simulator/CLOC/examples/snack/helloworld/HelloWorld -k /home/choi/Simulator/CLOC/examples/snack/helloworld/hw.asm

> Global frequency set at 1000000000000 ticks per second
warn: system.ruby.network adopting orphan SimObject param 'int_links'
warn: system.ruby.network adopting orphan SimObject param 'ext_links'
warn: DRAM device capacity (8192 Mbytes) does not match the address range assigned (512 Mbytes)
fatal: Number of ISAs (0) assigned to the CPU does not equal number of threads (1).
Memory Usage: 1170608 KBytes
choi@choi-desktop:~/Simulator/gem5$

I think some default values in "apu_se.py" are defined as invalid parameter, but I'm struggling to solve it.
Please give me some advices.

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
