### ISSUE TITLE
new SimObject fails to send a response packet due to crossbar problem

### ISSUE THREAD

**Issue by iliasslasri** [gem5/gem5#1353]
### Discussed in https://github.com/orgs/gem5/discussions/1352

<div type='discussions-op-text'>

<sup>Originally posted by **iliasslasri** July 16, 2024</sup>
Hello gem5 community,

I created a new SimObject that does just like the memory, the object has a Response port when it recieves a read command it sends a ReadResponse, but when it arrives to the xbar, the xbar fails to route it, and the assersion in line 454 in coherent_xbar.cc  `_assert(route_lookup != routeTo.end());` fails, however While debugging I made sure to have to send a Response packet and I just modify the data like this : `
pkt->setData(&value);
pkt->makeResponse();
port.sendTimingResp(pkt);`

More details : I just write a C code reading from the address I assigned to the module and the Request packet arrives to the new object and the REsponse packet succesufly leaves the new object and get to the xbar. the problem is just with the routing in the xbar, knowimg that I don't modify pkt->req, used by the xbar to remember the reauest came from where.

So I don't really know where the problem can come from, thank you all for your help.</div>

**Comment by ivanaamit** [comment]
This question has been answered at https://harmonylists.io/empathy/thread/R37EGMVOBCNV5CZC74F3EPIQMNWNFM6E.
