### ISSUE TITLE
The implementation of the Best Offset Prefetcher in Gem5 is not accurate to what the paper describes

### ISSUE THREAD

**Issue by Setu-Gupta** [gem5/gem5#1402]
The implementation of the Pierre Michaud's Best Offset Prefetcher (BOP) has some inconsistencies with respect to the [paper](http://www.irisa.fr/alf/downloads/michaud/dpc2_michaud.pdf) because of which the performance estimated of BOP are pessimistic. In particular
1. The hash computation which is used to index the RR Table results in a significant number of cache conflicts. This in turns hurts the performance due to the contention at the RR Table.
2. In the tag computation, which is done when an address is stored in the RR Table, the tag is computed incorrectly. In particular, the current version of code uses the following formula to compute the tag: `(addr >> blkSize) & tagMask`. For cache line sizes of 64 bytes, the `blkSize` variable has the value 64. However, if we right shift `addr` by 64, we end up either zeroing it out (if the compiler uses logical right shift), or not changing the value at all (if the compiler uses logical right shift with rotate). Note that the compiler is free to choose between the two types of right shift operations because we end up bit-wise ANDing the result anyways.
This, of course, is not what we want. Instead of `(addr >> blkSize) & tagMask`, the correct formula is `(addr >> lBlkSize) & tagMask` which performs the right shift not by the $block\ size$, but rather by the $log_2(block\ size)$. In our example, this would mean that we right shift by 6 instead of 64 which is the correct value since the BOP operates at cache line granularity (as opposed to word address granularity). 
3. The best offset learning algorithm which is implemented differs from what the paper describes. The pseudo-code for the current implementation is as follows:
```
if all offsets have been visited
	increment the round count
	if its time to choose a new offset
		choose the new offset
		enable prefetching
		reset learning structures
	else if the best score is less than the threshold
		disable prefetching
	endif
endif
```
In the current implementation, BOP will only choose a new offset if all offsets have been visited. However, if the first offset in the list of offsets is indeed the best offset (its score exceeds the prefetching threshold), then BOP should not wait until it tests all offsets to choose the first offset. To fix this issue, the psuedocode needs to be be broken into two independent parts: the first part which checks if all offsets have been visited and updates the data structures, and the second part which performs the best offset selection. If we couple these two distinct pieces together, then BOP would have to wait until all offsets have been evaluated before it can select the new best offset. This, in turn, reduces the reaction time of BOP as it would not be able to react quickly to the changes in workload's memory access patterns. If the workload's access offset changes from $o_1$ to $o_2$, then until all offsets have been evaluated, BOP would not update the best offset from $o_1$ to $o_2$. This would not be a problem for workloads with fairly long intervals of constant offsets, but for workloads which frequently change their access pattern, the current of implementation of BOP would not be able to provide good coverage.

My colleague and I have fixed the code and we want to contribute our implementation to upstream. I'm creating this issue so that I can open a pull request.

**Comment by erin-le** [comment]
Closing due to PR 1403, which fixes this issue, being merged.
