### ISSUE TITLE
Add Pannotia GPU Tests

### ISSUE THREAD

**Issue by BobbyRBruce** [gem5/gem5#1422]
This was once a desire which was attempted, but eventually abandoned, in this PR: https://github.com/gem5/gem5/pull/259.

**Comment by mattsinc** [comment]
I was not aware the GPU tests had been removed from weekly.  What was the issue?

**Comment by BobbyRBruce** [comment]
> I was not aware the GPU tests had been removed from weekly. What was the issue?

I'm going to make not toe check and see if we accidentally dropped these at somepoint thinking they have "translated" via this PR (which was never merged)... I'm have hard time remember what changed when, though I can say they aren't in the weekly tests right now.

**Comment by erin-le** [comment]
Pannotia GPU tests have been added
