### ISSUE TITLE
Stats Resetting

### ISSUE THREAD

**Issue by studyztp** [gem5/gem5#1443]
Currently, there does not exist a documentation or clear guidance about what stats in the stats.txt file that can be reset by the `m5.stats.reset()` function and what stats cannot.
For example, the stats `simInsts` does not reset when calling `m5.stats.reset()`.

**Comment by BobbyRBruce** [comment]
Shouldn't it reset?

I'm wondering  if you're suggesting we document which stats are, and which are not, wiped, or if there are stats that should be reset but aren't.

My feeling is `m5.stats.reset()` should reset _all_ stats... no?

**Comment by studyztp** [comment]
Sadly, `m5.stats.reset()` is not resetting all the stats in the stats file. 
I attached a simple run script that can show that (it is modified from [arm-hello.py](https://github.com/gem5/gem5/blob/stable/configs/example/gem5_library/arm-hello.py)). This script exits the simulation after simulating the workload for 143293729 Ticks, then dump and reset the stats using `m5.stats.reset()` and `m5.stats.dump()`. It then falls back to the simulation for only 1 Ticks then dump the stats before exit. The stats file should suggest that `simInsts` did not get reset.

We've been noticing `simInsts` is not being reset, but maybe there are more. 
I suggest testing out what stats in the stats file that can or cannot be reset first, then depending on what stats are actually having issue, we can decide if we should document them, wipe them, or fix them.
If it's only `simInsts` that is being an issue, I think we can fix it or add the warning in its stat description. 

```
from gem5.components.boards.simple_board import SimpleBoard
from gem5.components.cachehierarchies.classic.no_cache import NoCache
from gem5.components.memory import SingleChannelDDR3_1600
from gem5.components.processors.cpu_types import CPUTypes
from gem5.components.processors.simple_processor import SimpleProcessor
from gem5.isas import ISA
from gem5.resources.resource import obtain_resource
from gem5.simulate.simulator import Simulator
from gem5.utils.requires import requires
import m5

# This check ensures the gem5 binary is compiled to the ARM ISA target. If not,
# an exception will be thrown.
requires(isa_required=ISA.ARM)

# In this setup we don't have a cache. `NoCache` can be used for such setups.
cache_hierarchy = NoCache()

# We use a single channel DDR3_1600 memory system
memory = SingleChannelDDR3_1600(size="32MB")

# We use a simple Timing processor with one core.
processor = SimpleProcessor(cpu_type=CPUTypes.TIMING, isa=ISA.ARM, num_cores=1)

# The gem5 library simble board which can be used to run simple SE-mode
# simulations.
board = SimpleBoard(
    clk_freq="3GHz",
    processor=processor,
    memory=memory,
    cache_hierarchy=cache_hierarchy,
)

# Here we set the workload. In this case we want to run a simple "Hello World!"
# program compiled to the ARM ISA. The `Resource` class will automatically
# download the binary from the gem5 Resources cloud bucket if it's not already
# present.
board.set_se_binary_workload(
    # The `Resource` class reads the `resources.json` file from the gem5
    # resources repository:
    # https://github.com/gem5/gem5-resources.
    # Any resource specified in this file will be automatically retrieved.
    # At the time of writing, this file is a WIP and does not contain all
    # resources. Jira ticket: https://gem5.atlassian.net/browse/GEM5-1096
    obtain_resource("arm-hello64-static", resource_version="1.0.0")
)

# Lastly we run the simulation.
simulator = Simulator(board=board)
simulator.run(143293729)
m5.stats.dump()
m5.stats.reset()
simulator.run(1)
m5.stats.dump()

print(
    "Exiting @ tick {} because {}.".format(
        simulator.get_current_tick(), simulator.get_last_exit_event_cause()
    )
)
```
