### ISSUE TITLE
The implementation of the Stride prefetcher has a few bugs

### ISSUE THREAD

**Issue by Setu-Gupta** [gem5/gem5#1448]
**Describe the bug**
The current implementation of the Stride Prefetcher has the following three issues:
1. The stride prefetcher works at the granularity of cache lines. Therefore, for computing the stride, the prefetcher should use cache line aligned addresses, and not word aligned addresses
2. Since the prefetcher would be notified on every word access, if  a workload reads multiple bytes from a single cache line (which happens a lot), then when the prefetcher observes access to words $w_1$ and $w_2$ such that both of the words lie in the same cache line, the prefetcher would end up computing the stride to be 0. This, by itself is not an issue, but since the prefetcher updates its confidence counters based on the computed and the last observed stride, this computation would reduce the confidence value, thereby reducing the effectiveness of the prefetcher.
3. If the current version of the prefetcher finds that the new stride does not match the old stride, it still issues prefetches using the new stride even though the new stride has not crossed the confidence threshold yet. This, in turn, can result in a whole lot of useless prefetches which hurt the accuracy and put unnecessary pressure on the memory subsystem.

**Affects version**
The version of Gem5 on the develop branch

My colleague (@AbhishekUoR) and I have fixed the issue and we are opening a PR for it. This issue is just there to ensure that everyone knows about why the PR is being opened in the first place

**Comment by BobbyRBruce** [comment]
Fixed by #1449
