### ISSUE TITLE
Membus encountered multiple HBMCtrls configured to respond to the same address range (SE Mode)

### ISSUE THREAD

**Issue by LujhCoconut** [gem5/gem5#1462]
**Briefly describe the bug encountered**
In the latest version of Gem5, utilizing the HBMCtrl memory controller and connecting it to the system.membus results in a fatal error, specifically indicating that 'system.membus has two ports responding within the same address range.'

**gem5 Modifications**
The Gem5 environment has undergone minimal modifications, with changes limited to the addition of command-line parameter information in Options.py and the inclusion of configuration details specific to the SPEC CPU2017 benchmark. These adjustments are not expected to impact the issues related to the existing bugs.

**To Reproduce**
In short,
(1) create address ranges
```python
start = 0
end = 8*1024
mem_range = AddrRange(str(start) + 'MiB', str(end) + 'MiB')
system.mem_ranges.append(mem_range)
```

(2) create memory controllers according to  address ranges and number of HBM controllers 
```python
    for r in system.mem_ranges:
        intlv_bits = int(math.log(nbr_hbm_ctrls, 2))
        if 2 ** intlv_bits != nbr_hbm_ctrls:
            fatal("Number of memory channels must be a power of 2")
        for i in range(nbr_hbm_ctrls):
            intf = ObjectList.mem_list.get(opt_hbm_type)
            hbm_intf = create_mem_intf(intf, r, i,
                                intlv_bits, intlv_size, opt_xor_low_bit)
            hbm_ctrl = m5.objects.HBMCtrl()
            hbm_ctrl.dram = hbm_intf
            hbm_ctrl.dram_2 = hbm_intf
            mem_ctrls.append(hbm_ctrl)
```

(3) Attach to the membus
```python
    for i in range(len(mem_ctrls)):
        if opt_mem_type == "HMC_2500_1x32":
            mem_ctrls[i].port = xbar[i/4].mem_side_ports
            mem_ctrls[i].dram.device_size = options.hmc_dev_vault_size
        else:
            mem_ctrls[i].port = xbar.mem_side_ports
    subsystem.mem_ctrls = mem_ctrls
```

(4) Then, run simulation ! Fatal occurs !
```shell
system.remote_gdb: Listening for connections on port 7000
src/mem/xbar.cc:436: fatal: system.membus has two ports responding within range [0:0x200000000] a[9]=0 a[10]=0 a[11]=0 a[12]=0 a[13]=0 a[14]=0:
        system.mem_ctrls00.port
        system.mem_ctrls00.port
Memory Usage: 8606508 KBytes
```

**Terminal Input**
```shell
$GEM5_DIR/build/X86/gem5.opt -d $GEM5_DIR/x86_trace/x86_hbm/$BENCHMARK_CODE --debug-flags=MemoryAccess --debug-file=$BENCHMARK_CODE.out $GEM5_DIR/configs/hybrid/hbm_only_se.py --num-cpus=1 --cpu-type=TimingSimpleCPU \
--cpu-clock=2200MHz --caches --l2cache  --num-l2caches=1  --num-l3caches=1   --mem-type=DDR4_3200_4x16 --hbm-type=HBM_1000_4H_1x128 \
--benchmark=$BENCHMARK -I 1000000000
```

**Expected behavior**
Everything runs smoothly, just like configuring MemCtrl.

**Host Configruation**
Ubuntu 18.04, x86-84, gcc-10, g++-10

**Additional information**
Since HBMCtrl inherits from MemCtrl, it is designed with a single port. Based on the intended connection architecture, linking this port to the bus should not introduce any issues.
```python
class HBMCtrl(MemCtrl):
    type = "HBMCtrl"
    cxx_header = "mem/hbm_ctrl.hh"
    cxx_class = "gem5::memory::HBMCtrl"
    dram_2 = Param.DRAMInterface("DRAM memory interface")
    min_reads_per_switch = 64
    min_writes_per_switch = 64
```
```python
class MemCtrl(QoSMemCtrl):
    type = "MemCtrl"
    cxx_header = "mem/mem_ctrl.hh"
    cxx_class = "gem5::memory::MemCtrl"
    # single-ported on the system interface side, instantiate with a
    # bus in front of the controller for multiple ports
    port = ResponsePort("This port responds to memory requests")
    dram = Param.MemInterface(
        "Memory interface, can be a DRAMor an NVM interface "
    )
```

**Comment by powerjg** [comment]
>             hbm_ctrl.dram = hbm_intf
>            hbm_ctrl.dram_2 = hbm_intf

These need to be two different interface instances.

See https://github.com/gem5/gem5/blob/stable/src/python/gem5/components/memory/hbm.py for an example.
