### ISSUE TITLE
Fix style in RISC-V isa file

### ISSUE THREAD

**Issue by powerjg** [gem5/gem5#147]
https://github.com/gem5/gem5/blob/dceabe5fda598937b00959cc648fb7f2fbbe950a/src/arch/riscv/isa.hh#L73C19-L73C19

This should be `rvType` instead of `rv_type`.

**Comment by rogerchang23424** [comment]
I think `pcstate.hh` also need to be fix
https://github.com/gem5/gem5/blob/dceabe5fda598937b00959cc648fb7f2fbbe950a/src/arch/riscv/pcstate.hh

**Comment by Harshil2107** [comment]
Pushed changes to ```pcstate.hh```.
