### ISSUE TITLE
No error reported but fail to link or generate an .opt file.

### ISSUE THREAD

**Issue by liuyuxivapor** [gem5/gem5#1536]
**Describe the bug**
No error reported but fail to link or generate an .opt file.

**Affects version**
24.0

**gem5 Modifications**
Nothing changed compared to the repo.

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

1. Compile gem5 with command `scons build/X86/gem5.opt -j10`

**Terminal Output**

```shell
<lots of outputs>
 [SO Param] m5.objects.Sequencer, RubyPort -> X86/python/_m5/param_RubyPort.cc
 [     CXX] src/base/date.cc -> X86/base/date.o
scons: done building targets.
*** Summary of Warnings ***
Warning: Header file <capstone/capstone.h> not found.
         This host has no capstone library installed.
Warning: Couldn't find HDF5 C++ libraries. Disabling HDF5 support.
```

**Expected behavior**

**Host Operating System**
Ubuntu 20.04

**Host ISA**
X86

**Additional information**
It seems that I have installed all requirements, but it still appears no error!

**Comment by Harshil2107** [comment]
It looks like you are building gem5 with just 1 thread so it will take a long time. I would recommend trying to build gem5 with more than one thread using the `-j` command. you can use `nproc` to get the total number of threads you have on your system. To build gem5 you can use `scons build/X86/gem5.opt -j16` for example.

**Comment by liuyuxivapor** [comment]
> It looks like you are building gem5 with just 1 thread so it will take a long time. I would recommend trying to build gem5 with more than one thread using the `-j` command. you can use `nproc` to get the total number of threads you have on your system. To build gem5 you can use `scons build/X86/gem5.opt -j16` for example.

I have tried this with `-j10`, but got the same problem. :( Thanks a lot anyway.

**Comment by giactra** [comment]
Have you tried to redirect stderr to file to check if there is a linkage error line you have missed in the terminal?

`scons build/X86/gem5.opt -j10 2> error.log`

**Comment by Mr-Cong** [comment]
The same error. I have solved it! Use the tar.gz version or unzip the zip version in Linux, not in Windows.

**Comment by Harshil2107** [comment]
It looks like the issue was solved. I am closing the issue as resolved.

**Comment by liuyuxivapor** [comment]
> Have you tried to redirect stderr to file to check if there is a linkage error line you have missed in the terminal?
> 
> `scons build/X86/gem5.opt -j10 2> error.log`

Acctually I have done this before, but no error occurred.

**Comment by abmerop** [comment]
I was also seeing this issue, mainly when changing branches a lot, but wasn't able to find a fix. I basically had to delete the build directory and recompile. I am commenting to acknowledge that this issue exists for others too.

**Comment by erin-le** [comment]
Duplicate
