### ISSUE TITLE
Throw error when setting a workload more than once

### ISSUE THREAD

**Issue by powerjg** [gem5/gem5#1543]
Each board should only have `set_workload` or `set_kernel_disk_workload`, etc. called once. If it's called multiple times, strange (and difficult to debug) errors appear. 

In the workload mixin classes, we should check to make sure it hasn't already been called and raise and exception (or fatal) if it has. Alternatively, we could have a warning, but I think an error is more appropriate.

**Comment by erin-le** [comment]
Could not reproduce; only observed that the simulation ran the second workload that was set.
