### ISSUE TITLE
show build information bug

### ISSUE THREAD

**Issue by ShuangqiLi** [gem5/gem5#1591]
**Describe the bug**
I got "module 'm5.defines' has no attribute 'gem5Version' " when using -B option

**Affects version**
24.0.0.1

**To Reproduce**
```
gem5.opt --build-info
```
or
```
gem5.opt -B
```

**Terminal Output**

```shell
AttributeError: module 'm5.defines' has no attribute 'gem5Version'

At:
  src/python/m5/main.py(443): main
```

I tried to fix it by using _m5.core.gem5Version instead of defines.gem5Version according to line 514. (the same for compileDate)
It just worked but I'm not sure that's the best.

**Comment by powerjg** [comment]
Thanks for the bug report! Your fix sounds OK to me. It would be greatly appreciated if you created a PR with the fix and we can discuss more there.
