### ISSUE TITLE
GitHub Actions Runner VMs are limited to 60GB Disk Space. This means disabling PARSEC Tests

### ISSUE THREAD

**Issue by BobbyRBruce** [gem5/gem5#165]
Our GitHub self-hosted Actions Runners run within VMs. These VMs are limited to a 60GB of disk image space. This is sufficient for most tests, but if running PARSEC, we are required to download the PARSEC Disk Image resource, v1.0.0 (http://resources.gem5.org/resources/x86-parsec?version=1.0.0). Unzipped this image is 33GB, which pushes the VM to exaust all it's disk image space. This crashes the VM.

Pull Request #164 disables the tests which use PARSEC.

The PARSEC tests can be re-incorporated when we are able to increase the disk image size on these VMs.

**Comment by abmerop** [comment]
Trying to understand this more, does this mean that gem5, build, etc.  plus the disk image size must currently fit in 60GB?  I.e., what are the other 27GB (=60GB - 33GB) being used for?  I want to understand since a GPU full system test would need a disk of similar size (~31 GB), if one is ever added.

**Comment by BobbyRBruce** [comment]
> Trying to understand this more, does this mean that gem5, build, etc. plus the disk image size must currently fit in 60GB? I.e., what are the other 27GB (=60GB - 33GB) being used for? I want to understand since a GPU full system test would need a disk of similar size (~31 GB), if one is ever added.

The downloaded zip of the image still exists as it's being unzipped. I think we're short of about 2GB when it's being decompressed and the VM fails. I think the zip is about 12GB. The remainder is the OS, gem5, and the gem5 build. So it's something like:

~33G : The Disk image uncompressed.
~12GB: The Disk image zipped.
~15GB: OS, GitHub Actions runner, gem5, and its dependencies.

**Comment by BobbyRBruce** [comment]
Yip, this is no longer a restriction, though I still have yet to reenable PARSEC, however to do so, i believe we need KVM available on our runners. This is a seperate issues: long-story-short, I can't get KVM working with gem5 in a docker container, in our GitHub Actions service, in one of our runner VMs, on server. I'm sure there's a way but I've yet to figure it out.
