### ISSUE TITLE
gem5 is not building for RISCV

### ISSUE THREAD

**Issue by soniab** [gem5/gem5#1706]
version used: gem5-24.0.0.0.tar.gz
I have also tried with git clone https://github.com/gem5/gem5.git

**modules used:** 
module load python/3.12.3 
 module load llvm/18.1.4
module load scons/4.2.0 
module load gcc/12.2.0 

command used:
scons  build/RISCV/gem5.opt -j4 > build_log.txt

**Issue:** gem5.opt has not been created inside build/RISCV
I can see only the following folders:
soniar@login1:/cfs/klemming/projects/snic/naiss2023-23-49/sonia/gem5-new/gem5-24.0.0.0> ls build/RISCV/
arch  base  config  cpu  debug  dev  enums  ext  gem5.build  gem5py  gem5py_m5  kern  learning_gem5  mem  params  python  sim  sst  systemc

I checked available targets:
The predefined targets currently available are:

          ALL
          ARM
          ARM_MESI_Three_Level
          ARM_MESI_Three_Level_HTM
          ARM_MOESI_hammer
          Garnet_standalone
          MIPS
          NULL
          NULL_MESI_Two_Level
          NULL_MOESI_CMP_directory
          NULL_MOESI_CMP_token
          NULL_MOESI_hammer
          POWER
          RISCV
          RISCV_old
          SPARC
          VEGA_X86
          X86
          X86_MESI_Two_Level
          X86_MI_example
          X86_MOESI_AMD_Base

**I can see only one error:** 
Error: A PrgEnv-* modulefile must be loaded.
readelf: Error: 'nefZx5pux.o': No such file
ext/libelf/elf.c:34:46: error: expected expression before ',' token
   34 |         .libelf_arch            = LIBELF_ARCH,
But I am not sure that it should impact anything

[build_log.txt](https://github.com/user-attachments/files/17494199/build_log.txt)

**Comment by erin-le** [comment]
Duplicate
