### ISSUE TITLE
Typo in gem5-resources/riscv-matrix-multiply

### ISSUE THREAD

**Issue by joaquintorres** [gem5/gem5#1814]
In https://resources.gem5.org/resources/riscv-matrix-multiply/ `resource_id` is `arm-matrix-multiply` instead of `riscv-matrix-multiply`. See the screenshot below.
![screenshot](https://github.com/user-attachments/assets/d74aa707-f763-41b0-ae01-94dcebf8f87d)

**Comment by powerjg** [comment]
@Harshil2107 can you take a look at this? Thanks!

**Comment by Harshil2107** [comment]
Fixed

![image](https://github.com/user-attachments/assets/f0fa06f4-18f5-452b-84fc-b4dd78bf9e80)

**Comment by Harshil2107** [comment]
closing issue as fixed.
