### ISSUE TITLE
Add workload to resource specialization of resources.py and deprecate workload.py

### ISSUE THREAD

**Issue by Harshil2107** [gem5/gem5#193]
At present, there exist two pathways for resource acquisition: the first involves the utilization of the `obtain_resource()` function, while the second entails employing the `Workload` class found within `workload.py` for workloads only. Remarkably, both of these approaches leverage a shared function to access the JSON resources. Notably, a workload itself can be conceptualized as a resource. As part of an enhancement, we can create a dedicated "workload resource," thereby rendering the current `workload.py` obsolete. This transition would involve deprecating `workload.py` into a wrapper encapsulating the functionality of `obtain_resources()`. 

Successful implementation depends on issue #192  requiring updates to all workloads before pushing this change.

**Comment by BobbyRBruce** [comment]
There is no dependency between this as #192, they just both changes to the Workload. This makes `Workload` an `AbstractResource` implementation. #192 fixes an issue in `Workload` where the version of the Resources used are not specified. They are is no dependency. One can be done before or after the other, they are just both modifying the same code.
