### ISSUE TITLE
run result in gem5

### ISSUE THREAD

**Issue by HADOUDA** [gem5/gem5#20]
hello, please help me;
i need to run the parsec benchmarck in gem5 
I copied parsec in the .img image and i used the following command:
sudo scons FULL-SYSTEM = 1 build / ARM / gem5.opt -disk-image = expanded-linux-aarch32-ael.img -kernel = vmlinux-aarch32-ll-20131205 -script =. / path / script.rcS
with a .rcs script for each application for example (blackscholes), and I found this result for all parsec applications:

-sh: ./blackscholes: Permission denied

**Comment by cirosantilli-work** [comment]
While I can't help with those images, I can provide a working parsec setup at: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/e8f09a76e6b40f61f4b445a40eb28eb4f36a7392#parsec-benchmark

Also, please spend some time to:

- write better titles, into full sentences, and more detail
- familiarize yourself with GitHub's markdown: https://guides.github.com/features/mastering-markdown/
