### ISSUE TITLE
Port gem5 common modules to work in multi-ISA setups

### ISSUE THREAD

**Issue by giactra** [gem5/gem5#216]
As mentioned in #215, common clients (like se.py) are not multi-ISA compatible.

```
Exception: Cannot determine the the runtime ISA. Either the 'TARGET_ISA' parameter must be set or the binary only compiled to one ISA.

    At:
      src/python/gem5/runtime.py(84): get_runtime_isa
      .../gem5/configs/common/Caches.py(101): PageTableWalkerCache
      .../gem5/configs/common/Caches.py(91): <module>
      <frozen importlib._bootstrap>(241): _call_with_frames_removed
      <frozen importlib._bootstrap_external>(940): exec_module
      <frozen importlib._bootstrap>(705): _load_unlocked
      <frozen importlib._bootstrap>(1150): _find_and_load_unlocked
      <frozen importlib._bootstrap>(1176): _find_and_load
      .../gem5/configs/common/CacheConfig.py(48): <module>
      <frozen importlib._bootstrap>(241): _call_with_frames_removed
      <frozen importlib._bootstrap_external>(940): exec_module
      <frozen importlib._bootstrap>(705): _load_unlocked
      <frozen importlib._bootstrap>(1150): _find_and_load_unlocked
      <frozen importlib._bootstrap>(1176): _find_and_load
      <frozen importlib._bootstrap>(241): _call_with_frames_removed
      <frozen importlib._bootstrap>(1233): _handle_fromlist
      .../gem5/configs/deprecated/example/se.py(61): <module>
      src/python/m5/main.py(630): main
```

It is likely possible to work around the problem, but the real solution is to stop using the [get_runtime_isa](https://github.com/gem5/gem5/blob/stable/src/python/gem5/runtime.py#L55) function in those files and embrace having multiple ISAs. The ISA of a specific processing element can be retrieved by the cpu object itself rather than the TARGET_ISA environment variable.

This would probably be a mid-term solution until we eventually deprecate/remove the common library from gem5

**Comment by BobbyRBruce** [comment]
I'm going to create a PR which removes [`get_runtime_isa`](https://github.com/gem5/gem5/blob/f29bfc0640c88a79eb7f94454ce31b3237ec0066/src/python/gem5/runtime.py#L55) from gem5 completely. It's a deprecated function and has been deprecated for several releases now. It's time for it to go.

The way users should specify the ISA is by selecting the right CPU  class when setting up their simulation (e.g., `X86KvmCPU` or `ArmSimpleTimingCPU`). Using the [`requires`](https://github.com/gem5/gem5/blob/f29bfc0640c88a79eb7f94454ce31b3237ec0066/src/python/gem5/utils/requires.py#L53) function also helps to ensure the ISA you want to simulate is compiled into the binary.

The `get_runtime_isa` function is just a relic from the time we had single ISA-target builds and used that ISA-target as the setting of the simulated system's ISA. It was always a bit weird.

I may need help removing `get_runtime_isa` from some of the "configs/common" code but I'll give it a go by myself first. I agree we need to handle "configs/common" for now even though our intention is to eventually deprecate this.
