### ISSUE TITLE
Is Branch Predictor working for Minor and DerivO3?

### ISSUE THREAD

**Issue by silvaurus** [gem5/gem5#24]
I'm having problem retrieving the BTB hit rate for both Minor and DerivO3.
The problem for Minor is that, inside of the branch predictor bpred_unit,cc, it uses functions like static_inst.isControl(), static_inst.isConditional() etc, which use instruction flags to decide if this is a branch. While at the fetch stage when we do prediction, the instruction flags have not been decided yet and always has a default all-zero.

Previously I brute force one program to get all of its branch PCs (conditional, unconditional, branch etc), creating a list. Every time those instructions are called, I just searched those lists.

This works for Minor. But in DeriveO3, there is yet another problem. The function inst->branchTarget() called in decode_impl.hh is simply not implemented. In static_inst.cc, the function simply output a panic.
TheISA::PCState
StaticInst::branchTarget(const TheISA::PCState &pc) const
{
    panic("StaticInst::branchTarget() called on instruction "
          "that is not a PC-relative branch.");
    M5_DUMMY_RETURN;
}

I'm wondering if there's something wrong with my configuration. Since the main objective for me to run gem5 is to get a BTB hit rate, I'm in urgent need to make this work. Thank you so much for your help!

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
