### ISSUE TITLE
Website is not displaying correctly.

### ISSUE THREAD

**Issue by cnjsdfcy** [gem5/gem5#266]
Hi there,

I'm not sure if it's just me or someone else also encountering the website displaying problem, please help take a look since it's preventing smooth reading of the documents. Thanks~

![image](https://github.com/gem5/gem5/assets/5670527/9b2d0f1c-4838-41ce-927c-2fb3ef23dd3e)

**Comment by Harshil2107** [comment]
Hi,
Can you send the link to the page you are viewing? I checked the documentation page of the gem5 website and the footer is being rendered differently for me. I have attached a screenshot of how it looks on my system.

<img width="960" alt="image" src="https://github.com/gem5/gem5/assets/91860903/6289ab84-ff13-409b-83df-8701fe1c8948">

**Comment by cnjsdfcy** [comment]
Hi @Harshil2107 ,

The link is https://www.gem5.org , and I tried both Chrome and Edge, both had the same rendering issue.

Thanks.

**Comment by Harshil2107** [comment]
I looked on my end, The website looks the same as the screenshot I sent above. I tried different aspect ratios and window sizes, but I couldn't reproduce the rendering issue you were having. 

Are there any other details that you can give to help me reproduce the issue?

Thanks.

**Comment by cnjsdfcy** [comment]
Hi @Harshil2107 ,

After fixed the DNS of company, the web is rendering OK.

Thanks and closing the ticket.
