### ISSUE TITLE
Incorrect special file comparisons in Linux kernel

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#269]
**Describe the bug**
The path string comparisons in src/kern/linux/linux.cc function `Linux::openSpecialFile()` do not check for string equality but rather equality of prefixes.
This causes `"/proc/self/maps0123456789"` to compare "equal" to `"/proc/self/maps"`, so a program accessing that invalid file path will actually access `"/proc/self/maps"`.

**Affects version**
develop @ 48a40cf

**gem5 Modifications**
None

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:
1. Compile the following program `bug.c` with the command `cc -static -o bug bug.c`:
```c
#include <stdio.h>
#include <stdlib.h>

int main() {
  FILE *f = fopen("/proc/self/maps0123456789", "r");
  if (f == NULL) {
    // correct path
    perror("fopen");
    return EXIT_FAILURE;
  } else {
    // actual path
    char line[256];
    while (fgets(line, sizeof line, f))
      printf("%s", line);
  }
}
```
1. Compile gem5 with command `scons build/X86/gem5.opt`
2. Execute the simulation with `./build/X86/gem5.opt configs/deprecated/example/se.py -c ./bug`
3. Observe it happily print out the contents of "/proc/self/maps", rather than printing an error.

**Expected behavior**
The above program should print "fopen: No such file or directory", not print out the contents of a different file, "/proc/self/maps".

**Host Operating System**
Ubuntu 20.04

**Host ISA**
X86

**Compiler used**
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by BobbyRBruce** [comment]
Closed by #270
