### ISSUE TITLE
sim-se: syscall emulation of newfstatat returns invalid data in stat struct

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#281]
**Describe the bug**
The syscall emulation of newfstatat, implemented in `newfstatatFunc()` in src/sim/syscall_emul.hh, treats the output stat buffer as the old the old OS::tgt_stat struct, not the new OS::tgt_stat64 struct as it should. Here's a program to demonstrate the bug:
```c
#include <unistd.h>
#include <stdio.h>
#include <sys/stat.h>
#include <syscall.h>
#include <fcntl.h>
#include <stddef.h>

#define PRINT(name, type)			\
  printf(#name "=" type "\n", st.st_##name)

int main(int argc, char *argv[]) {
  struct stat st;
  if (stat(argv[0], &st) < 0) {
    perror("stat");
    return 1;
  }
  PRINT(dev, "%lu");
  PRINT(ino, "%lu");
  PRINT(mode, "0x%x");
  PRINT(nlink, "%lu");
  PRINT(uid, "%u");
  PRINT(gid, "%u");
  PRINT(rdev, "%lu");
  PRINT(size, "%zu");
  PRINT(blksize, "%zu");
  PRINT(blocks, "%zu");
}
```
Running this program on the host and in gem5 SE should print the same output; however, the output of the gem5 SE run indicates that the stat buffer is corrupt (e.g., on my machine, the mode is 0 when it should be 0x81ed).

**Affects version**
develop @ 48a40cf

**gem5 Modifications**
None

**To Reproduce**
1. Compile the attached C program, 
[stat.c.zip](https://github.com/gem5/gem5/files/12551250/stat.c.zip): `cc -static -o stat stat.c`
2. Compile gem5: `scons build/X86/gem5.opt`
3. Run on the host to see expected output: `./stat`.
4. Run in gem5 SE to see buggy output: `./build/X86/gem5.opt configs/deprecated/example/se.py --cmd=./stat`

**Expected behavior**
Both the host and gem5 SE runs should produce (roughly) identical output; the `st.st_mode` field under gem5 SE should *definitely* not be zero.

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86

**Compiler used**
GCC 11.4.0 

**Additional information**
None

**Comment by BobbyRBruce** [comment]
Fixed by #283.
