### ISSUE TITLE
sim-se: syscall emulation of tgkill always returns EINVAL

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#284]
**Describe the bug**
Due to a small logic bug, the syscall emulation of tgkill, implemented in `tgkillFunc()` in src/sim/syscall_emul.hh, always returns `-EINVAL` (invalid argument). Specifically, the logic bug is due to the following code using an "or" instead of an "and", resulting in an always-true condition:
```c
if (sig != 0 || sig != OS::TGT_SIGABRT)
    return -EINVAL;
```
So when the application makes the following call to tgkill(2), it exits with "Invalid argument" instead of aborting the program:
```c
if (syscall(SYS_tgkill, getpid(), gettid(), SIGABRT)) {
    perror("tgkill");
    exit(1);
}
```

**Affects version**
develop @ 84e0224

**gem5 Modifications**
None

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:
1. Compile the attached C program, [tgkill.c.zip](https://github.com/gem5/gem5/files/12552568/tgkill.c.zip): `cc -static -o tgkill tgkill.c`
1. Compile gem5 with command `scons build/X86/gem5.opt`
2. Execute the simulation with `build/X86/gem5.opt configs/deprecated/example/se.py --cmd=./tgkill`

If possible, please include the Python configuration script used and state clearly any parameters passed.

**Terminal Output**
```
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version DEVELOP-FOR-23.1
gem5 compiled Sep  7 2023 11:48:37
gem5 started Sep  7 2023 12:03:58
gem5 executing on cafe3.stanford.edu, pid 138003
command line: ./build/X86/gem5.fast configs/deprecated/example/se.py --cmd=./tgkill

warn: The `get_runtime_isa` function is deprecated. Please migrate away from using this function.
warn: The se.py script is deprecated. It will be removed in future releases of  gem5.
warn: The `get_runtime_isa` function is deprecated. Please migrate away from using this function.
Global frequency set at 1000000000000 ticks per second
warn: No dot file generated. Please install pydot to generate the dot file and pdf.
src/mem/dram_interface.cc:690: warn: DRAM device capacity (8192 Mbytes) does not match the address range assigned (512 Mbytes)
src/base/statistics.hh:279: warn: One of the stats is a legacy stat. Legacy stat is a stat that does not belong to any statistics::Group. Legacy stat is deprecated.
system.remote_gdb: Listening for connections on port 7000
**** REAL SIMULATION ****
src/sim/simulate.cc:194: info: Entering event queue @ 0.  Starting simulation...
src/sim/mem_state.cc:443: info: Increasing stack size by one page.
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
tgkill: Invalid argument
Exiting @ tick 13663000 because exiting with last active thread context
Simulated exit code not 0! Exit code is 1
```

**Expected behavior**
The program should simply abort, like:
```sh
$ ./tgkill
Aborted
```

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86

**Compiler used**
GCC 11.0.4

**Additional information**
None

**Comment by BobbyRBruce** [comment]
Fixed by #286.
