### ISSUE TITLE
Non-deterministic simulation results

### ISSUE THREAD

**Issue by ivanaamit** [gem5/gem5#289]
Running gem5 built with two different compilers is giving different results by ~0.1% This is a pretty big issue, and it's been reproduced in a number of different simulations. 

When running this script (run_stream_3.py) sometimes we see 185085400 ticks and sometimes we see 185411800 ticks.
We haven't narrowed down exactly how to reproduce it, but we are working on it.

[script.zip](https://github.com/gem5/gem5/files/12562224/script.zip)

**Comment by BobbyRBruce** [comment]
I created #300 to add some tests to find this. In doing so I observed the following (note: I use the `x86-ubuntu-run-to-tick.py` script which is in the #300):

```sh
./build/ALL/gem5.opt --stats-file=json://stats-baseline-1.json configs/example/gem5_library/x86-ubuntu-run-to-tick.py --ticks 1000000
./build/ALL/gem5.opt --stats-file=json://stats-baseline-2.json configs/example/gem5_library/x86-ubuntu-run-to-tick.py --ticks 1000000
diff <(jq 'del(.creation_time)' stats-baseline-1.json | jq --sort-keys .) <(jq 'del(.creation_time)' stats-baseline-2.json | jq --sort-keys .)
```

The following is output (top 20 lines):

```sh
14247c14247
<             "underflow": 2.317153539e-314,
---
>             "underflow": 2.298907924e-314,
14281c14281
<             "underflow": 2.3171548436e-314,
---
>             "underflow": 2.2989092285e-314,
14335c14335
<             "underflow": 2.3254696917e-314,
---
>             "underflow": 2.3072240767e-314,
14358c14358
<             "overflow": 2.3285561396e-314,
---
>             "overflow": 2.3103105245e-314,
14362c14362
<             "underflow": 2.3171540847e-314,
---
>             "underflow": 2.2989084696e-314,
```

Few comments:

1. Why is "overflow" and "underflow" being set to these _insane_ values?
2. Even taking this into account, with floating-point weirdness, these values should be deterministic and not change between runs.

I think we have some undefined behavior here.

**To clarify:** This is the same compiler and same build of gem5.

**Comment by powerjg** [comment]
I think this might be a json printing problem, and I think it's different than what Ivana initially posted. I wonder if you didn't use json if this problem would go away.

**Comment by BobbyRBruce** [comment]
> I think this might be a json printing problem, and I think it's different than what Ivana initially posted. I wonder if you didn't use json if this problem would go away.

You're right. I don't know really why... I still think it should be deterministic.

I've updated #300 to use the txt file instead. It could be incorporated to see how our gem5 compilations differ.
