### ISSUE TITLE
generateDiassembly

### ISSUE THREAD

**Issue by forever-gk** [gem5/gem5#3]
In the arm arch, the output of diassembly has some mistakes. The diassembly can only output misc_reg index, like x461. The "dest" varible in every static_inst object is not relative, so the output is wrong. I use some tricks to fix this.

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
