### ISSUE TITLE
TraceCPU broken after multi-ISA addition

### ISSUE THREAD

**Issue by giactra** [gem5/gem5#301]
**Describe the bug**
As reported by Kashish Mittal in a gem5 [slack thread](https://gem5-workspace.slack.com/archives/C03JKFR639T/p1692813519155859), it is currently not possible to replay elastic traces from the [TraceCPU](https://www.gem5.org/documentation/general_docs/cpu_models/TraceCPU).
It is evident from the error message and from a quick investigation that the problem is the lack of definition of the architectural classes a BaseCPU requires:

- ArchDecoder
- ArchMMU
- ArchInterrupts
- ArchISA

These were originally (when the TraceCPU was written) set at compile time with the TARGET_ISA variable; therefore the TraceCPU was automatically inheriting them from the BaseCPU. Now the BaseCPU does not set them anymore, and it requires those ISA classes to be set from the child CPU classes:

```
class ArmCPU:
    ArchDecoder = ArmDecoder
    ArchMMU = ArmMMU
    ArchInterrupts = ArmInterrupts
    ArchISA = ArmISA
```

https://github.com/gem5/gem5/blob/stable/src/arch/arm/ArmCPU.py#L40

The TraceCPU has not been updated with such logic therefore any trace replay attempt produces the following error:

```
command line: build/ARM/gem5.opt -d bzip_10Minsts_replay configs/example/etrace_replay.py --cpu-type=TraceCPU --caches --data-trace-file=bzip_10Minsts/deptrace.proto.gz --inst-trace-file=bzip_10Minsts/fetchtrace.proto.gz --mem-size=4GB

warn: The `get_runtime_isa` function is deprecated. Please migrate away from using this function.
AttributeError: object 'TraceCPU' has no attribute 'ArchMMU'
  (C++ object is not yet constructed, so wrapped C++ methods are unavailable.)

At:
  src/python/m5/SimObject.py(847): __getattr__
  src/cpu/BaseCPU.py(303): __init__
  configs/example/etrace_replay.py(79): <module>
  src/python/m5/main.py(629): main
```

**Affects version**
v22.1, v23.0

**Comment by BobbyRBruce** [comment]
Fixed by #302
