### ISSUE TITLE
X87 floating-point FSTP/FISTP does not pop FP register

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#344]
**Describe the bug**
The family of X86 FPU instructions `fstp <op>` and `fistp <op>` do not pop `st(0)`, the top floating-point register, off of the x87 floating-point stack, resulting in incorrect results of subsequent x87 FPU instructions.
Specifically, this bug appears to originate from the fact that the [`popx87` micro-op](https://github.com/gem5/gem5/blob/958eda6961bc4e2b3b9bb52089c491eaf59353d6/src/arch/x86/isa/microops/fpop.isa#L430) does not in fact pop st(0) off the x87 FP stack.

Here is a simple example demonstrating the bug:
```c
#include <stdio.h>
int main() {
  int x = 1;
  int y = 2;
  asm volatile ("fild dword ptr [%0]\n"
                "fild dword ptr [%1]\n"
                "fistp dword ptr [%1]\n"
                "fistp dword ptr [%0]\n"
                :
                : "r"(&x), "r"(&y));
  printf("x = %d\n", x);
  printf("y = %d\n", y);
}
```
In gem5 SE, this incorrectly prints out `x = 2` and `y = 2`.

**Affects version**
develop @ [958eda6](https://github.com/gem5/gem5/commit/958eda6961bc4e2b3b9bb52089c491eaf59353d6)

**gem5 Modifications**
None

**To Reproduce**
1. Compile the example program: `cc -static -masm=intel -o fstp fstp.c`
2. Compile gem5: `scons build/X86/gem5.opt`
3. Run the program on the host: `./fstp`
4. Run the program in gem5 SE: `./build/X86/gem5.opt configs/deprecated/example/se.py --cmd ./fstp`

**Terminal Output**
When run with gem5, ./fstp outputs:
```
x = 2
y = 2
```

**Expected behavior**
When run on the x86 host, ./fstp outputs:
```
x = 1
y = 2
```

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86

**Compiler used**
GCC 11.4.0

**Additional information**
I'll submit a PR shortly.

**Comment by BobbyRBruce** [comment]
Fixed by #345
