### ISSUE TITLE
improperly initialized x86 PLATFORM auxv entry

### ISSUE THREAD

**Issue by nmosier** [gem5/gem5#346]
**Describe the bug**
The `AT_PLATFORM` auxiliary vector (auxv) entry is improperly initialized in src/arch/x86/process.cc:
```c
    // Fix up the aux vectors which point to data
   ...
    assert(auxv[auxv.size() - 1].type == gem5::auxv::Platform);
    auxv[auxv.size() - 1].val = aux_data_base + numRandomBytes;
   ...
    initVirtMem->writeString(aux_data_base, platform.c_str());
```
The AT_PLATFORM auxv value points to address `aux_data_base + numRandomBytes`, but the platform string (on x86, it's `x86_64`) is incorrectly copied to address `aux_data_base`. This accidentally clobbers the AT_RANDOM aux data but leaves the AT_PLATFORM aux data uninitialized.

Here is a C program to demonstrate the bug:
```c
#include <sys/auxv.h>
#include <stdio.h>
int main() {
  printf("platform: \"%s\"\n", (const char *) getauxval(AT_PLATFORM));
}
```

**Affects version**
develop @ [958eda6](https://github.com/gem5/gem5/commit/958eda6961bc4e2b3b9bb52089c491eaf59353d6)

**gem5 Modifications**
None

**To Reproduce**
1. Compile the above C program: `cc -static -o auxv auxv.c`
2. Compile gem5: `scons build/X86/gem5.opt`
3. Run the program on the host: `./auxv`
4. Run the program under gem5 SE: `./build/X86/gem5.opt configs/deprecated/example/se.py --cmd ./auxv`

**Terminal Output**
When run under gem5 SE mode, the program incorrectly outputs:
```
platform: ""
```

**Expected behavior**
The program prints this on the host:
```
platform: "x86_64"
```

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86

**Compiler used**
GCC 11.4.0

**Additional information**
I will submit a PR shortly

**Comment by BobbyRBruce** [comment]
Fixed by #347
