### ISSUE TITLE
How to build gem5 with cmake?

### ISSUE THREAD

**Issue by naveen126** [gem5/gem5#413]
Hi, Sir,
I want to build gem5 with cmake. Is there any tips to be followed? Thanks a lot!

**Comment by powerjg** [comment]
gem5 uses scons as its build system. See the following documentation for details. You cannot build gem5 with cmake.

https://www.gem5.org/getting_started/
https://www.gem5.org/documentation/learning_gem5/part1/building/
https://www.gem5.org/documentation/general_docs/building

https://www.youtube.com/watch?v=U4xThpRC1AI&ab_channel=gem5
