### ISSUE TITLE
Tests: Update gem5 SST tests to use SST 13.0.0

### ISSUE THREAD

**Issue by Harshil2107** [gem5/gem5#436]
PR #396 updates gem5 SST bridge. 

We should update the tests as well: https://github.com/gem5/gem5/blob/develop/tests/deprecated/nightly.sh#L154

Here is the Dockerfile used for testing https://github.com/gem5/gem5/tree/develop/util/dockerfiles/sst-11.1.0.

**Comment by BobbyRBruce** [comment]
Closed by #396
