### ISSUE TITLE
Missing install target and prefix option

### ISSUE THREAD

**Issue by rodarima** [gem5/gem5#481]
Hi, I'm packaging gem5 for NixOS and I have observed that the install target is missing.

I have never used scons or gem5 before, but as observed from other build tools like autotools or cmake, the usual approach is to fist configure and build the software and then install it in a given `prefix` path.

As explained in the [scons documentation](https://scons.org/doc/latest/HTML/scons-design/ch04s06.html#idp105548897397064), the install action can be defined with:

```python
env.Install('/usr/bin', 'program1', 'program2')
```
However, I don't see any definition of such `env.Install` operations:

```
% grep env.Install $(find . -name SConstruct) | wc -l
0
```

Combined with the [AddOption](https://scons.org/doc/latest/HTML/scons-user/ch10.html#idp105548963450696), it can allow the prefix to the given from the command line.

From the Default target:

```python
Default(environ.get('M5_DEFAULT_BINARY', 'build/ARM/gem5.debug'))
```

Would it be safe to assume that only the gem5.xxx binary is needed? I could prepare a patch if only this is needed.

**Affects version**
I'm testing on the last release 23.0.1.0, but I assume it has always been this way.

**gem5 Modifications**
No modifications.

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

```
$ scons build/ALL/gem5.opt --prefix=/path/to/my/gem5/installation
$ scons build/ALL/gem5.opt install
```

**Expected behavior**

Gem5 should be installed to /usr/local (or any other directory given by `prefix`.

**Host Operating System**
NixOS, but I believe could be reproduced in any other.

**Host ISA**
X86

**Compiler used**
gcc 12.3.0

**Comment by Harshil2107** [comment]
Incorporating gem5 into an application is a significant long-term objective, as many use cases necessitate source code modifications. Presently, utilizing `scons install` with gem5 is not viable.

**Comment by andysan** [comment]
Another point in all of this is that the gem5 binary is designed to be self-contained and without assumptions about its install path. The original intention was that you would be able to build gem5 and just copy the binary to a cluster environment and run it there (this makes assumptions about the C/C++ standard library though). In practice, that means that the value of an install target is very limited, especially since most users need to modify the code anyway.

**Comment by rodarima** [comment]
> In practice, that means that the value of an install target is very limited, especially since most users need to modify the code anyway.

I understand that most use cases require modification on the source code, but I don't think it is mutually exclusive with having an install target. We allow developers use their own gem5 repository or custom patches and still provide a package for it.

The rationale (for us) is that once we have built a gem5 package we generate a unique hash that can trace back the steps required to obtain the same binary (same source commit, dependencies, configuration options, etc.) which is good for reproducibility when publishing a paper. Here is an example of the dependencies we used in our particular build:

```
hut% nix-store --query -R /nix/store/vv666glhv5c7y7az8gdlk2cmlr7fypkj-gem5-23.0.1.0
/nix/store/5cfwfnp4capzbjmkkrl7a6shvaghgj3h-xgcc-12.3.0-libgcc
/nix/store/748caky83gr4pyrhircvi4llx99ja6z9-libunistring-1.1
/nix/store/v5llm7rmipvg487yvgb15q0m2jxrihq3-libidn2-2.3.4
/nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8
/nix/store/ir0j7zqlw9dc49grmwplppc7gh0s40yf-bash-5.2-p15
/nix/store/p9a2nhhpa2dwyw1sy5gr4482ddqmwpkx-zlib-1.2.13
/nix/store/00p99k85wnww6i54508ga57gp1rwyc13-hdf5-1.14.1-2
/nix/store/1ql93amj3rmq5yg7qry7ky6gwpbvdgxp-ncurses-6.4
/nix/store/3dx3yvw5pjshch7ckjvf5zl8ic8wq91d-readline-8.2p1
/nix/store/4di6g7ckk729cjrs9l6aqi5731sx4fw7-openssl-3.0.9
/nix/store/kbjir9mdrz2w1f7kl4ikisg491x2xd1y-gcc-12.3.0-libgcc
/nix/store/4igdc32rmnijcra8y3r1h42987ghzag2-gcc-12.3.0-lib
/nix/store/70i27j50bn0zj2zgbxww087xhbg60ps6-libxcrypt-4.4.36
/nix/store/bg6dzgvw2wpg61v8a7f0x6fkm31k26hh-libffi-3.4.4
/nix/store/cnlf5ww1hgqhynq1g2f73k4ahbdpav7v-expat-2.5.0
/nix/store/d6h42ly2lqrai8xnyw1apx0rnknfmlfc-sqlite-3.42.0
/nix/store/jzwb72mdcsqna9sh79wgk3rjfvp8a7i5-tzdata-2023c
/nix/store/nqr0hwhybhx7jz6lz1xhazl4d9fvf03c-bzip2-1.0.8
/nix/store/q723yrnx2nkwz3a0f7i5yb9pzj942cf8-mailcap-2.1.53
/nix/store/zgdi1h5pjwvxk3s4s7jfp2xknk8xy1px-gdbm-1.23
/nix/store/zrhgwwrdipfmjy3kawr0sf93y2f0x0qs-xz-5.4.3
/nix/store/2c7sgx69p6mmp76cvmi5j6c72dj76jj8-python3-3.10.12
/nix/store/g7rl6c7hll9sfiqa7yxv5bcr266myd5y-libunwind-1.6.2
/nix/store/84l91kcmxs3d5gvmwgddzqj66yk3vv1x-gperftools-2.10
/nix/store/h2h5fs8iv2a8rmlkfhr6id6y4jxwd5i1-protobuf-3.21.12
/nix/store/mppz0yhlnna153fmw03hd4r364mq07z6-libpng-apng-1.6.39
/nix/store/s9z0ai95q0gjiqz1xq70r0dfah0jnvs2-hdf5-cpp-1.14.1-2
/nix/store/vv666glhv5c7y7az8gdlk2cmlr7fypkj-gem5-23.0.1.0
```

If you only require copying the gem5 binary to the final destination, then adding an install target sounds doable.

I tried to do it myself, but I think it would require the build process to record which targets are to be build (debug, opt and/or fast), and then the install process would read those and installs them. I guess this can be done with the sticky variables (notice I'm not familiar with scons). The build and install steps are generally separated because the build is done without extra privileges and the install may require root.

As I'm only installing the `gem5.opt` target, as a workaround for now I just copy the binary manually:

```nix
  # Gem5 is missing a install phase. We simply copy the generated binary as-is.
  installPhase = ''
    mkdir -p $out/bin
    cp -a build/ALL/gem5.opt $out/bin
  '';
```

However, I still see the gem5 binary has additional paths pointing to `$ORIGIN` in its runpath (those directories are empty in my build):

```
hut% readelf -d /nix/store/vv666glhv5c7y7az8gdlk2cmlr7fypkj-gem5-23.0.1.0/bin/gem5.opt | grep runpath | tr ':' '\n'
 0x000000000000001d (RUNPATH)            Library runpath
 [$ORIGIN/./arch/arm/fastmodel/CortexR52/x1/gcc
$ORIGIN/./arch/arm/fastmodel/CortexR52/x1
$ORIGIN/./arch/arm/fastmodel/CortexR52/x2/gcc
$ORIGIN/./arch/arm/fastmodel/CortexR52/x2
$ORIGIN/./arch/arm/fastmodel/CortexR52/x3/gcc
$ORIGIN/./arch/arm/fastmodel/CortexR52/x3
$ORIGIN/./arch/arm/fastmodel/CortexR52/x4/gcc
$ORIGIN/./arch/arm/fastmodel/CortexR52/x4
$ORIGIN/./arch/arm/fastmodel/PL330_DMAC/gcc
$ORIGIN/./arch/arm/fastmodel/PL330_DMAC
$ORIGIN/./arch/arm/fastmodel/GIC/gcc
$ORIGIN/./arch/arm/fastmodel/GIC
$ORIGIN/./arch/arm/fastmodel/CortexA76/x1/gcc
$ORIGIN/./arch/arm/fastmodel/CortexA76/x1
$ORIGIN/./arch/arm/fastmodel/CortexA76/x2/gcc
$ORIGIN/./arch/arm/fastmodel/CortexA76/x2
$ORIGIN/./arch/arm/fastmodel/CortexA76/x3/gcc
$ORIGIN/./arch/arm/fastmodel/CortexA76/x3
$ORIGIN/./arch/arm/fastmodel/CortexA76/x4/gcc
$ORIGIN/./arch/arm/fastmodel/CortexA76/x4
/nix/store/2c7sgx69p6mmp76cvmi5j6c72dj76jj8-python3-3.10.12/lib
/nix/store/84l91kcmxs3d5gvmwgddzqj66yk3vv1x-gperftools-2.10/lib
/nix/store/p9a2nhhpa2dwyw1sy5gr4482ddqmwpkx-zlib-1.2.13/lib
/nix/store/00p99k85wnww6i54508ga57gp1rwyc13-hdf5-1.14.1-2/lib
/nix/store/s9z0ai95q0gjiqz1xq70r0dfah0jnvs2-hdf5-cpp-1.14.1-2/lib
/nix/store/mppz0yhlnna153fmw03hd4r364mq07z6-libpng-apng-1.6.39/lib
/nix/store/h2h5fs8iv2a8rmlkfhr6id6y4jxwd5i1-protobuf-3.21.12/lib
/nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib
/nix/store/4igdc32rmnijcra8y3r1h42987ghzag2-gcc-12.3.0-lib/lib]
```

**Comment by andysan** [comment]
Models that use the FastModel integration seems to be the only exception to the linking rules. I haven't really looked in detail at the way these are built, but I suspect there would need to be a bit of work done on the build system to do this properly.

If you really need to package gem5 with FastModels, I would suggest that you just copy the generated FastModel libraries into a lib directory in the target and patch up the gem5 binary using a tool like `chrpath`.

**Comment by powerjg** [comment]
As an aside, it would be nice to know who I'm talking to :smile:. If you could let us know your name and affiliation, that would be appreciated!

Overall, I have not heard from the community that an install directive would help their use cases, but it sounds like it's useful to you. As of now, since there is no need from the general community, there is no developer that is planning to add this support. If you want to submit a changeset, we can review it. If your PR is self-contained, doesn't cause any problems with common use cases, and doesn't add a significant maintenance burden, we would be happy to include the change in upstream gem5.

**Comment by BobbyRBruce** [comment]
I am closing this issue as it appears to have been sufficiently discussed and has led to no specific task for developers to perform at this time.
