### ISSUE TITLE
[bug] interrupt pin is not connected(binded) when simulate with cxxManager to parsing the configuration

### ISSUE THREAD

**Issue by gxflying** [gem5/gem5#524]
Hi sirs,  I recently do some work on  simulating the riscv full-system in a  gem5 within systemc environment 
and I had run in coredump,  
by debug this issue ， I found that is OK when the simulation runs with python config file , But it run in coredump when the simulation runs with a config.ini which is parsed by cxxManager !
and the root cause is that the interrupt pin of riscv rtc **is not binded to clint int_pin** when parsed by cxxManager as the python parser will   be

when I try to go far into this problem,  I found that it is because the interrupt pin(port) does set the  **isRequestor** correctly in the cxxManager flow.
https://github.com/gem5/gem5/blob/e9da8d67bdbb23fbd0578a379f08f42bce50121d/src/sim/cxx_manager.cc#L548
and the incorrect set of **isRequestor** is because in the cxx_config_cc.py does not check the role type of the interrupt pin which is "Int Source Pin"
https://github.com/gem5/gem5/blob/e9da8d67bdbb23fbd0578a379f08f42bce50121d/src/dev/IntPin.py#L28
https://github.com/gem5/gem5/blob/e9da8d67bdbb23fbd0578a379f08f42bce50121d/build_tools/cxx_config_cc.py#L107

and **the solution of this bug is simple**， and I have tested this and the linux kernel had been booted successfully

is_requestor = port.role == "GEM5 REQUESTOR"    
= >  is_requestor = (port.role == "GEM5 REQUESTOR") or (port.role == "Int Source Pin")

while the solutiuon seems simple,  it really cosumed me some time to debug
and  Hope to help other persons who run into the same issue

**Comment by BobbyRBruce** [comment]
This is fixed by #196. It is currently on the `develop` branch but will be part of the upcoming v23.1 release.
