### ISSUE TITLE
Incorrect File Size from stat Syscall on x86_64 System

### ISSUE THREAD

**Issue by raindroid** [gem5/gem5#551]
**Describe the bug**
When running a C++ program that uses the `stat` syscall to read file sizes on an x86_64 system, gem5 returns incorrect file size values. This appears to be due to a type mismatch in the handling of the `struct stat` between the gem5 simulated environment and the actual x86_64 Linux system.

**Affects version**
Current Stable branch (hash: e9da8d67bdbb23fbd0578a379f08f42bce50121d)

**gem5 Modifications**
N/A

**To Reproduce**
Steps to reproduce the behavior.

1. Compile gem5 with command: `scons build/X86/gem5.opt -j 10 CPU_MODELS=AtomicSimpleCPU,TimingSimpleCPU,O3CPU,MinorCPU`
2. Execute the simulation with a C++ program using the `stat` syscall to read file sizes.
    ```c++
    struct stat fileStat;
    if (stat(argv[1], &fileStat) == -1) {
        std::cerr << "Error: Unable to get file status.\n";
        return 1;
    }
    std::cout << "File size in bytes: " << fileStat.st_size << "\n";    
    ```
- Python Script is simple
    ```python
    cache_hierarchy = PrivateL1PrivateL2CacheHierarchy(
        l1d_size="32KiB",
        l1i_size="32KiB",
        l2_size="64KiB",
    )
    memory = SingleChannelDDR3_1600("3GiB")
    processor = SimpleProcessor(cpu_type=CPUTypes.O3, num_cores=1, isa=ISA.X86)
    
    board = SimpleBoard(clk_freq="1GHz", processor=processor,
                        memory=memory, cache_hierarchy=cache_hierarchy)
    
    # Set the workload
    print(f"Simulating workload {args.binary} with {args.args}.")
    binary = BinaryResource(
        local_path=args.binary,
    )
    stdin_file = FileResource(local_path=args.stdin) if args.stdin else None
    board.set_se_binary_workload(
        binary, arguments=args.args, stdin_file=stdin_file)
    
    # Run the simulation
    simulator = Simulator(board=board)
    simulator.run()
    ```

**Terminal Output**
I feed the program with a simple example.txt with only one line: `Hello world!` (12 chars)
This is the output (last two lines):
```
File size in bytes: 1699841049
Exiting @ tick 94794000 because exiting with last active thread context.
```
Note: this number is the same as another field in the `struct stat`
```gdb
(gdb) p fileStat
$1 = {st_dev = 2098, st_ino = 2126623, st_nlink = 1, st_mode = 33204, st_uid = 1000, st_gid = 1000, __pad0 = 0, 
  st_rdev = 0, st_size = 12, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1699841049, tv_nsec = 365473834}, 
  st_mtim = {tv_sec = 1699841049, tv_nsec = 293473876}, st_ctim = {tv_sec = 1699841049, tv_nsec = 293473876}, 
  __glibc_reserved = {0, 0, 0}}
```

**Expected behavior**
The expected behavior is that gem5 should return the correct file size as obtained when running the same program on an actual x86_64 Linux system. This is the output from directly executing the c++ code.
```
File size in bytes: 12
```

**Host Operating System**
Ubuntu 22.04.3

**Host ISA**
x86_64 (Intel i7-11700k)

**Compiler used**
g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Python 3.10.11

**Additional information**
The core of the issue seems to be a mismatch in the handling of the stat structure between gem5's simulated environment and a native x86_64 Linux system. I observed that in the gem5 environment, the stat syscall is processed by the `newfstatatFunc`. This function uses `VPtr<typename OS::tgt_stat>` for the returned file status. However, upon inspecting the relevant headers in gem5 (specifically `arch/x86/x86/linux/linux.hh`), I noticed that for x86_64 systems, the structure defined is `X86Linux::tgt_stat64`and not `tgt_stat`. The tgt_stat structure has a bit-level mismatch when interpreting the file size in a 64-bit context. To address this issue, I tried to change `VPtr<typename OS::tgt_stat>` to `Ptr<typename OS::tgt_stat_64>` in `newfstatatFunc`, which led to the correct file size being returned, aligning with the results from a native x86_64 system. 

However, I assume the reason for `newfstatatFunc` is to be compatible with 32bit systems, so alternatively, one could consider modifying the syscall table in `arch/x86/linux/syscall_tbl64.cc` to ensure that syscall 262 (`newfstatat`) is mapped to function (`fstatat64Func`). This change also resolves the discrepancy in file size. The above findings indicate a need for a review and potential update of the syscall handling in gem5, specifically concerning the stat syscall in 64-bit environments, to ensure compatibility and correctness in file size reporting.

**Comment by BobbyRBruce** [comment]
This was fixed by https://github.com/gem5/gem5/pull/283, though it's still on our `develop` branch and has yet to be incorporated into `stable`.

I don't think the intention of `newfstatatFunc` is to remain compatible with 32bit systems as it's only used in 64bit systems, so the fix made is safe.

**Comment by raindroid** [comment]
Thanks!
