### ISSUE TITLE
potential pull request

### ISSUE THREAD

**Issue by passioner** [gem5/gem5#6]
Hi,
our team is adding some new functions into GEM5 for tracing branch predictor and cache information（cache reuse/stack distance,branch resolution time,instruction critical path,etc.）, which is our CPI module's input. In the future, we hope this module can be a tool for CPU performance evaluation.
as front-end of our tool, we hope the additional tracing code in GEM5 to be official and reliable. so, will the pull request be acceptable?

Thanks,
Wang Wei.

**Comment by andysan** [comment]
Hi,

We can currently not accept pull requests on GitHub as the official contribution flow uses Gerrit for code review. The flow to submit new contributions is described in [CONTRIBUTING.md](https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md).

You might want to have a look at the existing trace functionality if want to trace stack distances. There is already infrastructure to measure stack distances and trace memory accesses (see src/mem/probes). This infrastructure can be wired up to the memory system as probes that attach to the the CommMonitor component.

Cheers,
Andreas
