### ISSUE TITLE
CHI protocol, XY routing algorithm Assertion `m_num_rows * m_num_cols == m_routers.size()' failed.

### ISSUE THREAD

**Issue by qqli579** [gem5/gem5#619]
**Describe the bug**
When using the CHI protocol to simulate a 2X2 mesh network and using the XY routing algorithm, the following error occurred:
src/mem/ruby/network/garnet/GarnetNetwork.cc:131: virtual void gem5::ruby::garnet::GarnetNetwork::init(): Assertion `m_num_rows * m_num_cols == m_routers.size()' failed.)

**Affects version**
v23.0.1.0   stable branch

**gem5 Modifications**
No solution yet

**To Reproduce**
1、git clone https://github.com/gem5/gem5.git
2、Add the config file 2X2.py in the configs/example/noc_config directory：
            from ruby import CHI_config
            class NoC_Params(CHI_config.NoC_Params):
                num_rows = 2
                num_cols = 2
            
            class CHI_RNF(CHI_config.CHI_RNF):
                class NoC_Params(CHI_config.CHI_RNF.NoC_Params):
                    router_list = [0, 3]
            
            class CHI_HNF(CHI_config.CHI_HNF):
                class NoC_Params(CHI_config.CHI_HNF.NoC_Params):
                    router_list = [2]
            
            class CHI_MN(CHI_config.CHI_MN):
                class NoC_Params(CHI_config.CHI_MN.NoC_Params):
                    router_list = [1]
            
            class CHI_SNF_MainMem(CHI_config.CHI_SNF_MainMem):
                class NoC_Params(CHI_config.CHI_SNF_MainMem.NoC_Params):
                    router_list = [3]
            
            class CHI_SNF_BootMem(CHI_config.CHI_SNF_BootMem):
                class NoC_Params(CHI_config.CHI_SNF_BootMem.NoC_Params):
                    router_list = [3]
            
            class CHI_RNI_DMA(CHI_config.CHI_RNI_DMA):
                class NoC_Params(CHI_config.CHI_RNI_DMA.NoC_Params):
                    router_list = [3]
            
            class CHI_RNI_IO(CHI_config.CHI_RNI_IO):
                class NoC_Params(CHI_config.CHI_RNI_IO.NoC_Params):
                    router_list = [3]

3、scons ./build/X86/gem5.debug PROTOCOL=CHI NUMBER_BITS_PER_SET=128 -j 64
4、Run the following command:
./build/X86/gem5.debug configs/deprecated/example/fs.py --ruby --mem-type=DDR4_2400_4x16 --cpu-type=O3CPU --mem-size=8GB --num-cpus=1 --num-dirs=1 --num-l3caches=1 --network=garnet --routing-algorithm=1 --topology=CustomMesh  --chi-config=./configs/example/noc_config/2x2.py --kernel=/.cache/gem5/x86-linux-kernel-4.19.83 --disk-image=/.cache/gem5/x86-npb

and then the following error will occur:
**** REAL SIMULATION ****
gem5::ruby::garnet::RoutingUnit::outportComputeXY(gem5::ruby::garnet::RouteInfo, int, gem5::ruby::PortDirection): Assertion `num_rows > 0 && num_cols > 0' failed.

If --mesh-rows=2 is added:
./build/X86/gem5.debug configs/deprecated/example/fs.py --ruby --mem-type=DDR4_2400_4x16 --cpu-type=O3CPU --mem-size=8GB --num-cpus=1 --num-dirs=1 --num-l3caches=1 --network=garnet --mesh-rows=2 --routing-algorithm=1 --topology=CustomMesh  --chi-config=./configs/example/noc_config/2x2.py --kernel=/.cache/gem5/x86-linux-kernel-4.19.83 --disk-image=/.cache/gem5/x86-npb

the following error will occur:
**** REAL SIMULATION ****
gem5.debug: src/mem/ruby/network/garnet/GarnetNetwork.cc:131: virtual void gem5::ruby::garnet::GarnetNetwork::init(): Assertion `m_num_rows * m_num_cols == m_routers.size()' failed.

From debugging, we found that the size of m_routers is 5
<img width="1110" alt="bug" src="https://github.com/gem5/gem5/assets/66655355/58cee4ea-37c3-42bf-91c3-212039917dff">

Judging from the generated dot.pdf file, there are indeed 5 routers, not 2x2=4.
<img width="612" alt="Snipaste_2023-11-29_15-54-29" src="https://github.com/gem5/gem5/assets/66655355/0c4fc6f7-6cce-49ee-939f-8e9de453284c">
The extra router is created by the _createRNFRouter function in configs/topologies/CustomMesh.py
<img width="871" alt="Snipaste_2023-11-29_15-56-29" src="https://github.com/gem5/gem5/assets/66655355/d570e81f-8ec9-4a38-b35d-2faacc5b4ab1">

Why do RNF nodes need a router to connect to the mesh network? Or the Mesh network of the CHI protocol does not support the XY routing algorithm

**Expected behavior**

**Host Operating System**
Ubuntu 22.04,

**Host ISA**
 X86

**Compiler used**
scons

**Additional information**
Using configs/example/noc_config/2x4.py will also produce the same error.

**Comment by powerjg** [comment]
First, please do not post picture of code. Please copy and paste the code and format it with markdown. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks for more information.

As far as the problem goes, I think this is a problem with your NoC configuration. I personally believe that *fundamentally* there is no way to have generic NoC configs that work for all protocols. If you want a 2x2 mesh, you should manually create it by creating the internal/external links and hooking them up correctly.

Furthermore, `fs/se.py` are unsupported and we cannot provide help when these scripts do not work. This is for the same reason as above. There are too many possible ways to use these scripts such that it is impossible to maintain them.

If there is a bug in garnet, please reopen this issue. Otherwise, if this is just a wrong configuration, then it is not something that we support as maintainers. We can't support every possible configuration of gem5, unfortunately :)
