### ISSUE TITLE
Release gem5 v23.1

### ISSUE THREAD

**Issue by BobbyRBruce** [gem5/gem5#660]
The gem5 staging branch has been created (#558). The staging branch can be found at https://github.com/gem5/gem5/tree/release-staging-v23-1.

The [release procedures](https://www.gem5.org/documentation/general_docs/development/release_procedures/) outlines the changes to be applied to the staging branch prior to a release. In addition to this, the branch will be intensely tested to ensure the gem5 v23.1 release is of acceptable quality.

It is possible for changes to be cherry-picked onto the staging branch during this time but this _should_ be reserved for changes which have a low probability of introducing disruptive functional change and bug fixes.

The following changes should be cherry-picked onto the staging branch once merged into `develop`

- [x] #447
    * [Under development. 1 developer days left]

- ~~#612~~
    * [Nice to have, though lack of resources to develop in time for release. Dropping]

## Cherry-picked to `release-staging-v23-1`

Via #682 : 
- [x] #658
- [x] #655
- [x] #654
- [x] #671
- [x] #675
- [x] #677
- [x] #674

Via #683
- [X] #666

Via #699 
- [X] #689
- [X] #510

Via #707 
- [X] #696 
- [X] #706 
- [X] #705 
- [X] #695 
- [X] #704 

Submitted directly to release staging:

- [X] #684
  * Cherry-picked back to develop: #698

**Comment by rogerchang23424** [comment]
Hi @BobbyRBruce,

I think the PR #674 should be cherry-pick in the gem5 v23.1. The RVV store instruction falsely mark as source because of the lack condition for `assignRE`. They should not mark as load.

**Comment by BobbyRBruce** [comment]
> Hi @BobbyRBruce,
> 
> I think the PR #674 should be cherry-pick in the gem5 v23.1. The RVV store instruction falsely mark as source because of the lack condition for `assignRE`. They should not mark as load.

Thanks! I've noted it down in the top comment. I'll be cherry-picked to staging soon.

**Comment by giactra** [comment]
Hi, I have this PR which is targeting the release-staging branch directly: https://github.com/gem5/gem5/pull/684
