### ISSUE TITLE
nvm config scripts do not work properly

### ISSUE THREAD

**Issue by ccccrrrr** [gem5/gem5#669]
**Describe the bug**
The given script `configs/nvm/sweep.py` and `configs/nvm/sweep_hybrid.py` do not work properly. 

**Affects version**
The latest version: [Version 23.0.1.0](https://github.com/gem5/gem5/releases/tag/v23.0.1.0)

**gem5 Modifications**
N/A

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

1. Compile gem5 with command `/usr/bin/env python3 $(which scons) build/X86/gem5.opt -j32`
2. Execute the simulation with `build/X86/gem5.opt configs/nvm/sweep.py` or `build/X86/gem5.opt configs/nvm/sweep_hybrid.py`

**Terminal Output**

```shell
command line: build/X86/gem5.opt configs/nvm/sweep.py

AttributeError: object 'HeteroMemCtrl' has no attribute 'dram'
  (C++ object is not yet constructed, so wrapped C++ methods are unavailable.)

At:
  src/python/m5/SimObject.py(847): __getattr__
  configs/nvm/sweep.py(122): <module>
  src/python/m5/main.py(630): main
```

and 

```shell
command line: build/X86/gem5.opt configs/nvm/sweep_hybrid.py

fatal: This script assumes the controller is a HeteroMemCtrl subclass
```

**Host Operating System**
Ubuntu 20.04.3 LTS

**Host ISA**
X86

**Compiler used**
gcc9.4.9, Python 3.8.10

**Additional information**
I think the problem lies in the memory creation process in `configs/common/MemConfig.py` does not match the expectations of memory creation in `config/nvm`.  For example, in `configs/nvm/sweep.py`, [line118](https://github.com/gem5/gem5/blob/461af5157552d916baec732dfc7d8e97a2e781d8/configs/nvm/sweep.py#L118):

```python
# the following assumes that we are using the native memory
# controller with an NVM interface, check to be sure
if not isinstance(system.mem_ctrls[0], m5.objects.MemCtrl):
    fatal("This script assumes the controller is a MemCtrl subclass")
if not isinstance(system.mem_ctrls[0].dram, m5.objects.NVMInterface):
    fatal("This script assumes the memory is a NVMInterface class")
```

the script assumes `system.mem_ctrl[0].dram` will store nvm interface, but in `configs/common/MemConfig.py`, [line256](https://github.com/gem5/gem5/blob/461af5157552d916baec732dfc7d8e97a2e781d8/configs/common/MemConfig.py#L256), there is:

```python
                # Create a controller if not sharing a channel with DRAM
                # in which case the controller has already been created
                if not opt_hybrid_channel:
                    mem_ctrl = m5.objects.HeteroMemCtrl()
                    mem_ctrl.nvm = nvm_intf

                    mem_ctrls.append(mem_ctrl)
                else:
                    ...
```
it just put nvm_intf in nvm. However, simply change the above `mem_ctrl.nvm` to `mem_ctrl.dram` does not solve the problem, and will cause other errors.

**Comment by BobbyRBruce** [comment]
I believe this is fixed by #1114 . Closing.
