### ISSUE TITLE
AMD APU gem5 simulator with HSA support

### ISSUE THREAD

**Issue by vrajeshlm** [gem5/gem5#7]
I am trying to build AMD APU simulator which supports Heterogeneous System Architecture (HSA) with internal graphics but to full system configuration of such system to build gem5 simulator is not known to me. 
All that I got is http://www.gem5.org/GPU_Models which contains some tutorial for AMD APU but I would like to use any prebuild full system APU simulator, if available.
Kindly help me on this.

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
