### ISSUE TITLE
Flags Request::READ_MODIFY_WRITE and Request::ACQUIRE are the same

### ISSUE THREAD

**Issue by tiagormk** [gem5/gem5#719]
The Request::READ_MODIFY_WRITE and Request::ACQUIRE flags are both 0x00020000:
https://github.com/gem5/gem5/blob/025ccadc6823eff93ee9e0a20712000978bbc53e/src/mem/request.hh#L161C15-L161C15

Is there a reason behind this or it's a bug ?

This doesn't break functionality, but the Ruby sequencer will check loads with Request::READ_MODIFY_WRITE set and will treat them as a store, which is not the intended behavior for a load-acquire.

**Comment by powerjg** [comment]
I'm pretty sure this is a bug. Here is where it was introduced: https://gem5-review.googlesource.com/c/public/gem5/+/48710

It looks like the ACQUIRE flag was overlooked. I don't see any problem picking a different unused bit for `READ_MODIFY_WRITE`

**Comment by ivanaamit** [comment]
@tiagormk, just following up on this. Does Jason's suggested change of selecting a different unused bit for `READ_MODIFY_WRITE` make sense?

**Comment by tiagormk** [comment]
Hi @ivanaamit , apologies for the lack of responsiveness. The solution makes sense. I will push a patch with the fix.

**Comment by tiagormk** [comment]
https://github.com/gem5/gem5/pull/922
