### ISSUE TITLE
Error when tracing is off causes failure

### ISSUE THREAD

**Issue by powerjg** [gem5/gem5#78]
The gem5 error. Should be a simple fix to import `fatal`

```
NameError: name 'fatal' is not defined

At:
  ../../src/gem5/python/m5/main.py(343): _check_tracing
  ../../src/gem5/python/m5/main.py(528): main
```

**Comment by powerjg** [comment]
If anyone is interested in picking this up, I would be happy to mentor you through your first commit with this issue :)

**Comment by LingkKang** [comment]
Hi, @powerjg, I tried to make a pull request but I'm not sure is everything all right.

Seems like `Change-Id` is missing in commit message but I can't find how to add it.
