### ISSUE TITLE
error: implicit conversion from 'int' to 'Element'

### ISSUE THREAD

**Issue by thanhp175** [gem5/gem5#8]
Hi, I am a beginner user of gem5. When I try to compile gem5, I got this error and many similar ones:

```In file included from build/ARM/arch/arm/generated/generic_cpu_exec_6.cc:11:
build/ARM/arch/arm/generated/exec-ns.cc.inc:189454:39: error: implicit conversion from 'int' to
      'Element' (aka 'signed char') changes value from 128 to -128 [-Werror,-Wconstant-conversion]
```
,which prevent me from compilation.

How could I overcome this error without any problem?

NOTE: I am compiling on OSX 10.12.4

Thanks and best regards,

Thanh C. Tran

**Comment by powerjg** [comment]
I am currently closing all issues on github and disabling the issue support.

If you have general gem5 questions, please use the gem5-users mailing list (http://www.gem5.org/mailman/listinfo/gem5-users).

Please report any issues/bugs to the gem5-dev mailing list (http://www.gem5.org/mailman/listinfo/gem5-dev). However, gem5 is an open source project, so you are encoraged to fix any bugs/issues you find an submit a review request on our review site: https://gem5-review.googlesource.com

More details can be found in the CONTRIBUTING file: https://gem5.googlesource.com/public/gem5/+/master/CONTRIBUTING.md
