### ISSUE TITLE
Fix daily tests failing due to removing gcn3_x86

### ISSUE THREAD

**Issue by Harshil2107** [gem5/gem5#825]
We're encountering daily test failures because the support for GCN3_X86 was removed in change #781 and daily tests are trying to build gem5 with GCN3_X86  to run the gpu tests. To address this issue and restore the functionality of the daily tests, the following steps are necessary:

- [x] Update gpu docker image to have dependencies for VEGA_X86. The PR for this change is #804 
- [x] Push this new docker image to cloud
- [x] Update the binaries used in the tests ( square and heterosync) to be built with VEGA_X86. PR https://github.com/gem5/gem5-resources/pull/22
- [x] Push these new binaries to the cloud
- [x] Update the workflow file for daily tests to uses these new images and binaries. PR #817 

These changes should make the daily tests pass.

We should also make the following changes to make sure these binaries are on gem5-resources

- [x] Create binary resources JSON and add them to the MongoDB database, so that these resources can be used with obtain_resources
- [x] Update the workflow file to use obtain_resource utility in gem5 to get the resources instead of wget.

The above two changes do not affect daily tests result.

**Comment by Harshil2107** [comment]
Pinging @mattsinc @abmerop and @BobbyRBruce on this.

**Comment by powerjg** [comment]
This looks like a good overview, @Harshil2107! Thanks for putting it together. Everyone else, could you check this to make sure it looks right to you?

**Comment by mattsinc** [comment]
I am not sure about the binary resources at the bottom, but the parts above that seem right.  I guess there is an open question about which binaries we want for all apps.  There are other GPU tests in the weekly runs -- but maybe we are compiling those instead of providing binaries because they use m5ops (for example)?

@abmerop since you took the lead here, it would be great if you can confirm.

**Comment by abmerop** [comment]
Looks like lulesh and HACC which i've upload too.

**Comment by powerjg** [comment]
I appreciate you building/uploading binaries. However, I would like to make sure that we are able to build the binaries. I want to make sure that we don't have any single points of failure and that building the binaries are well documented enough that multiple people can do it.

Two things we want to move away from:
1. Building binaries during testing. We should use only prebuilt binaries that have well documented build steps and source that is under our control.
2. wget. We want to move to using "resources" that can be found on resources.gem5.org and obtained via `obtain_resource`

**Comment by Harshil2107** [comment]
I merged the workflow file update PR in and re ran the gpu daily tests. They should pass

**Comment by Harshil2107** [comment]
Closing this Issue as the tests are passing and have been updated to use obtain_resource instead of wget.
