### ISSUE TITLE
Replace bitmanip test cases of asmtest resources with upstream one

### ISSUE THREAD

**Issue by rogerchang23424** [gem5/gem5#883]
The bitmanip test cases of `riscv-tests` is merged in upstream recently

https://github.com/riscv-software-src/riscv-tests/pull/539

We should revert the following CLs and bump the asmtest to the latest commit

[1] https://gem5-review.googlesource.com/c/public/gem5-resources/+/66651
[2] https://gem5-review.googlesource.com/c/public/gem5-resources/+/71699

**Comment by powerjg** [comment]
@Harshil2107 what is the status here?
