### ISSUE TITLE
Test support for Ubuntu 24.04

### ISSUE THREAD

**Issue by ivanaamit** [gem5/gem5#909]

**Comment by BobbyRBruce** [comment]
We need to get some things going with this. Ubuntu 24.04 is released on April 25th.

Listing here the Subtasks that needs done (I've made the markdown checkbox indicate the specific PRs I want to see. In one or two cases a step on completing a task may be dependent on creation of a PR (e.g., to create a PR to test a disk image, a gem5 Resources entry must be made and sources made available via another PR):


* [x] Update gem5 tests to use 24.04, thus ensuring gem5 compiles and runs in 24.04 environments. **Assigned to @BobbyRBruce**
    1. Add Dockerfiles for 24.04 all/min_dependencies to [util/dockerfiles](https://github.com/gem5/gem5/blob/116c483a42d6b5681614198c500261ed2e429528/util/dockerfiles) and update [docker-compose.yaml](https://github.com/gem5/gem5/blob/116c483a42d6b5681614198c500261ed2e429528/util/dockerfiles/docker-compose.yaml).
    2. Build Docker images locally : `cd util/dockerfiles && docker-compose build ubuntu-24.04_all-dependencies  ubuntu-24.04_min-dependencies`
    3. Test gem5 compilation in 24.04 by compiling ALL/gem5 in ubuntu-24.04 min and all dependencies images.
    4. Test gem5 execution in 24.04 by running tests in ubuntu-24.04-all-dependencies container (in container: `cd tests && ./main.py run --length=quick -j<num-procs> && ./main.py run --length=long -j<num-procs> && ./main.py run --length=very-long -j<num-procs>`)
    5. Push all/min docker images to our registry : `cd util/dockerfiles && docker-compose push ubuntu-24.04_all-dependencies ubuntu-24.04_min-dependencies` (@BobbyRBruce may be the only person who has permission to do this).
    6. Update ".github/workflow" files to use 24.04 min/all dependencies instead of 22.04.

* [x] Create a Ubuntu 24.04 boot-exit tests for ARM, RISCV and X86, thus ensuring gem5 can simulate a 24.04 system. **Assigned to @Harshil2107**
    1. Create an Ubuntu 24.04 boot image in gem5 Resources for ARM, RISCV and X86, like we do for 20.04 (e.g., https://resources.gem5.org/resources/riscv-ubuntu-20.04-img?version=1.0.0).
    2. Modify the boot-test already found in "tests/gem5/arm_boot_tests", "tests/gem5/riscv_boot_tests", and "tests/gem5/x86_boot_tests". Some 20.04/22.04 tests should be kept to ensure this still works, but upgrading most of them to 24.04 is advisable.

* [x] Extend SE mode tests with binaries compiled on 24.04 hosts, thus ensuring gem5 can run such binaries. **Assigned to @BobbyRBruce**
    1. Compile a selection of binaries used in "tests/gem5/se_mode" on an 24.04 host (or docker container). 
    2. Test running these binaries locally in SE mode on a 22.04 host or in a 22.04 docker container.
    3. Test running these binaries locally in SE mode on a 24.04 host or docker container.
    4. ~~[ ] Upload these binaries to gem5 Resources.~~
    5. Extend the tests in "tests/gem5/se_mode" to run these binaries.

* [x] Update website documentation to support 24.04 users **Assigned to @ivanaamit**

**Comment by BobbyRBruce** [comment]
> Update gem5 tests to use 24.04, thus ensuring gem5 compiles and runs in 24.04 environments. Assigned to @BobbyRBruce

Done via PR #1018. Will check this as complete once merged.

**Comment by BobbyRBruce** [comment]
> Extend SE mode tests with binaries compiled on 24.04 hosts, thus ensuring gem5 can run such binaries. Assigned to @BobbyRBruce

Done via #1031 (did not merge this as the tests seemed basic and rather pointless outside of this niche scenario.
