### ISSUE TITLE
Docker Image for Ubuntu 20.04 in the gem5 documentation is an incorrect version.

### ISSUE THREAD

**Issue by Shreesh-Kulkarni** [gem5/gem5#960]
The docker image for Ubuntu 20.04 in the documentation is an incorrect version. It redirects to 404 Page not found, and while pulling it via docker it says it doesn't exist. It should redirect to version 23:1 but the doc says its version 23:0. Documentation needs to update this.

Affects Ubuntu 20.04

Steps to reproduce the behavior. Please assume starting from a clean repository:

1. docker pull "ubuntu 20.04 image"
2. Error: image not found

**Comment by ivanaamit** [comment]
Hi @Shreesh-Kulkarni, thank you for reporting this bug.

Could you please provide us with a link to the documentation that you are referring to? Also, could you share the specific commands that you used? Thank you.

**Comment by EmilyG2413** [comment]
Hello! 

I was looking into this issue a bit more and I believe it is this [page](https://www.gem5.org/documentation/general_docs/building): https://www.gem5.org/documentation/general_docs/building
For this section: 
<img width="933" alt="image" src="https://github.com/gem5/gem5/assets/67800061/ad572aa7-f511-48c0-9732-0271979ac997">

I might be mistaken but hope this helps!

**Comment by ivanaamit** [comment]
@Shreesh-Kulkarni @EmilyG2413 This issue has been solved. There was a typo in the URL for 20.04.

**Comment by Shreesh-Kulkarni** [comment]
@ivanaamit thank you. It works now.
